### PR TITLE
Add default storage class and retain policy 

### PR DESCRIPTION
**Pull request by antejavor**
This PR adds a storage class with the `Retain` policy. Both lib and log storage will use dynamic storage class without the retain policy because of CI/CD and local development (minikube). For production deployments in AWS, Azure, and GCP, defaults need to change.

### CODE REVIEW

**Review by as51340 — CHANGES_REQUESTED** [review]
Can we add same thing for HA chart?

**Comment by antejavor** [comment]
@as51340, let's skip this change in HA for now, since, IMO it is not that critical.  

I have open an issue for this, so we can do it in next release: https://github.com/memgraph/helm-charts/issues/88

**Comment by as51340** [comment]
@antejavor But it's literally adding one file, what do we get by postponing it to next release. You want someone to try it or, what's the reason?

**Comment by antejavor** [comment]
Yeah, I would like to test different environments with standalone and then move to HA for different environments since it is easier and less expensive to test with standalone than with HA cluster 
 
 @as51340  As discussed on the call, let's do this in the next release to push this release as soon as possible.

**Pull request merged**
